name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env.testing

      - name: Generate Application Key
        run: |
          KEY=$(php artisan key:generate --env=testing --ansi --show)
          if grep -q '^APP_KEY=' .env.testing; then
            sed -i "s/^APP_KEY=.*/APP_KEY=$KEY/" .env.testing
          else
            echo "APP_KEY=$KEY" >> .env.testing
          fi

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Create SQLite database file
        run: touch database/testing.sqlite

      - name: Migrate testing DB
        run: php artisan migrate --env=testing --force

      - name: Tests
        run: php artisan test --env=testing
